// Gym exercises mapped to the GLB muscle node names they activate.
// primary = main movers (highlighted red), secondary = assisters (highlighted amber).

export type Exercise = {
  id: string;
  name: string;
  category: "Push" | "Pull" | "Legs" | "Core";
  equipment: string;
  cue: string;
  primary: string[];
  secondary: string[];
};

export const EXERCISES: Exercise[] = [
  {
    id: "bench-press",
    name: "Barbell Bench Press",
    category: "Push",
    equipment: "Barbell",
    cue: "Retract the scapula, drive feet into the floor, control the bar to the lower chest.",
    primary: ["Pectoralis_Major_Clavicular_Sternocostal_Abdominal"],
    secondary: ["Triceps_Lateral_Long_Heads", "Triceps_Medial_Head", "Deltoid_Anterior_Middle_Posterior"],
  },
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    category: "Push",
    equipment: "Dumbbell",
    cue: "Set a 30–45° bench, press the dumbbells together at the top.",
    primary: ["Pectoralis_Major_Clavicular_Sternocostal_Abdominal"],
    secondary: ["Deltoid_Anterior_Middle_Posterior", "Triceps_Lateral_Long_Heads"],
  },
  {
    id: "cable-fly",
    name: "Cable Chest Fly",
    category: "Push",
    equipment: "Cable",
    cue: "Slight elbow bend, squeeze the hands together at the midline.",
    primary: ["Pectoralis_Major_Clavicular_Sternocostal_Abdominal", "Pectoralis_Minor"],
    secondary: ["Deltoid_Anterior_Middle_Posterior"],
  },
  {
    id: "push-up",
    name: "Push-Up",
    category: "Push",
    equipment: "Bodyweight",
    cue: "Brace the core, lower under control, protract the shoulder blades at the top.",
    primary: ["Pectoralis_Major_Clavicular_Sternocostal_Abdominal", "Serratus_Anterior"],
    secondary: ["Triceps_Lateral_Long_Heads", "Rectus_Abdominis"],
  },
  {
    id: "dips",
    name: "Chest Dips",
    category: "Push",
    equipment: "Bodyweight",
    cue: "Lean forward to bias the chest, control the descent.",
    primary: ["Pectoralis_Major_Clavicular_Sternocostal_Abdominal"],
    secondary: ["Triceps_Lateral_Long_Heads", "Triceps_Medial_Head", "Deltoid_Anterior_Middle_Posterior"],
  },
  {
    id: "overhead-press",
    name: "Overhead Press",
    category: "Push",
    equipment: "Barbell",
    cue: "Squeeze glutes, bar over mid-foot, press the head 'through' at lockout.",
    primary: ["Deltoid_Anterior_Middle_Posterior"],
    secondary: ["Triceps_Lateral_Long_Heads", "Serratus_Anterior", "Trapezius"],
  },
  {
    id: "lateral-raise",
    name: "Dumbbell Lateral Raise",
    category: "Push",
    equipment: "Dumbbell",
    cue: "Lead with the elbows, pause at shoulder height, lower slowly.",
    primary: ["Deltoid_Anterior_Middle_Posterior"],
    secondary: ["Supraspinatus", "Trapezius"],
  },
  {
    id: "tricep-pushdown",
    name: "Tricep Pushdown",
    category: "Push",
    equipment: "Cable",
    cue: "Pin the elbows at your sides, full extension, squeeze at the bottom.",
    primary: ["Triceps_Lateral_Long_Heads", "Triceps_Medial_Head"],
    secondary: [],
  },
  {
    id: "pull-up",
    name: "Pull-Up",
    category: "Pull",
    equipment: "Bodyweight",
    cue: "Depress the scapula first, drive the elbows down, chest to the bar.",
    primary: ["Latissimus_Dorsi", "Teres_Major"],
    secondary: ["Biceps_Brachii", "Brachialis", "Rhomboideus_Major"],
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    category: "Pull",
    equipment: "Cable",
    cue: "Lean back slightly, pull to the upper chest, drive elbows toward hips.",
    primary: ["Latissimus_Dorsi", "Teres_Major"],
    secondary: ["Biceps_Brachii", "Rhomboideus_Major"],
  },
  {
    id: "barbell-row",
    name: "Barbell Row",
    category: "Pull",
    equipment: "Barbell",
    cue: "Hinge at the hips, pull to the lower chest, squeeze the shoulder blades.",
    primary: ["Latissimus_Dorsi", "Rhomboideus_Major", "Trapezius"],
    secondary: ["Biceps_Brachii", "Deltoid_Anterior_Middle_Posterior"],
  },
  {
    id: "cable-row",
    name: "Seated Cable Row",
    category: "Pull",
    equipment: "Cable",
    cue: "Sit tall, pull to the lower ribs, retract without shrugging.",
    primary: ["Latissimus_Dorsi", "Rhomboideus_Major"],
    secondary: ["Biceps_Brachii", "Trapezius"],
  },
  {
    id: "face-pull",
    name: "Face Pull",
    category: "Pull",
    equipment: "Cable",
    cue: "Pull to face level, externally rotate at the end, keep elbows high.",
    primary: ["Deltoid_Anterior_Middle_Posterior", "Infraspinatus"],
    secondary: ["Trapezius", "Rhomboideus_Major", "Teres_Minor"],
  },
  {
    id: "db-curl",
    name: "Dumbbell Curl",
    category: "Pull",
    equipment: "Dumbbell",
    cue: "Pin the elbows, supinate fully, slow on the way down.",
    primary: ["Biceps_Brachii", "Brachialis"],
    secondary: ["Brachioradialis"],
  },
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    category: "Pull",
    equipment: "Barbell",
    cue: "Keep elbows fixed, avoid swinging, full range.",
    primary: ["Biceps_Brachii", "Brachialis"],
    secondary: ["Brachioradialis"],
  },
  {
    id: "deadlift",
    name: "Conventional Deadlift",
    category: "Pull",
    equipment: "Barbell",
    cue: "Brace hard, bar over mid-foot, push the floor away.",
    primary: ["Gluteus_Maximus", "Biceps_Femoris_Long_Head", "Latissimus_Dorsi"],
    secondary: ["Trapezius", "Semitendinosus", "Iliocostalis_Lumborum"],
  },
  {
    id: "shrug",
    name: "Barbell Shrug",
    category: "Pull",
    equipment: "Barbell",
    cue: "Elevate straight up, pause at the top, no rolling.",
    primary: ["Trapezius"],
    secondary: [],
  },
  {
    id: "cable-external-rotation",
    name: "Cable External Rotation",
    category: "Pull",
    equipment: "Cable",
    cue: "Pin the elbow at your side, rotate the forearm outward slowly, control the return.",
    primary: ["Infraspinatus", "Teres_Minor"],
    secondary: ["Supraspinatus", "Deltoid_Anterior_Middle_Posterior"],
  },
  {
    id: "squat",
    name: "Barbell Back Squat",
    category: "Legs",
    equipment: "Barbell",
    cue: "Brace the core, knees track over the toes, hit depth.",
    primary: ["Rectus_Femoris", "Vastus_Lateralis", "Vastus_Medialis", "Gluteus_Maximus"],
    secondary: ["Adductor_Magnus", "Vastus_Intermedius", "Rectus_Abdominis"],
  },
  {
    id: "leg-press",
    name: "Leg Press",
    category: "Legs",
    equipment: "Machine",
    cue: "Feet shoulder-width, full range, don't lock the knees hard.",
    primary: ["Vastus_Lateralis", "Vastus_Medialis", "Rectus_Femoris"],
    secondary: ["Gluteus_Maximus", "Adductor_Magnus"],
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    category: "Legs",
    equipment: "Machine",
    cue: "Squeeze hard at the top, control the negative.",
    primary: ["Rectus_Femoris", "Vastus_Lateralis", "Vastus_Medialis", "Vastus_Intermedius"],
    secondary: [],
  },
  {
    id: "rdl",
    name: "Romanian Deadlift",
    category: "Legs",
    equipment: "Barbell",
    cue: "Hinge from the hips, soft knees, bar close to the body.",
    primary: ["Biceps_Femoris_Long_Head", "Semitendinosus", "Gluteus_Maximus"],
    secondary: ["Semimembranosus", "Iliocostalis_Lumborum"],
  },
  {
    id: "leg-curl",
    name: "Lying Leg Curl",
    category: "Legs",
    equipment: "Machine",
    cue: "Full range, pause at peak contraction, no hip lift.",
    primary: ["Biceps_Femoris_Long_Head", "Biceps_Femoris_Short_Head", "Semitendinosus"],
    secondary: ["Semimembranosus", "Gastrocnemius_Lateral_Medial"],
  },
  {
    id: "hip-thrust",
    name: "Barbell Hip Thrust",
    category: "Legs",
    equipment: "Barbell",
    cue: "Tuck the chin, full lockout, squeeze the glutes hard.",
    primary: ["Gluteus_Maximus"],
    secondary: ["Biceps_Femoris_Long_Head", "Gluteus_Medius", "Adductor_Magnus"],
  },
  {
    id: "lunge",
    name: "Walking Lunge",
    category: "Legs",
    equipment: "Dumbbell",
    cue: "Long stride, vertical torso, drive through the front heel.",
    primary: ["Gluteus_Maximus", "Rectus_Femoris", "Vastus_Lateralis"],
    secondary: ["Biceps_Femoris_Long_Head", "Gluteus_Medius", "Adductor_Magnus"],
  },
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    category: "Legs",
    equipment: "Machine",
    cue: "Full stretch at the bottom, pause at the top.",
    primary: ["Gastrocnemius_Lateral_Medial"],
    secondary: ["Soleus"],
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    category: "Legs",
    equipment: "Machine",
    cue: "Knees at 90°, squeeze hard at the top.",
    primary: ["Soleus"],
    secondary: ["Gastrocnemius_Lateral_Medial"],
  },
  {
    id: "calf-raise",
    name: "Calf Raise",
    category: "Legs",
    equipment: "Bodyweight",
    cue: "Full stretch, drive the ball of the foot down.",
    primary: ["Gastrocnemius_Lateral_Medial", "Soleus"],
    secondary: [],
  },
  {
    id: "single-leg-calf-raise",
    name: "Single Leg Calf Raise",
    category: "Legs",
    equipment: "Bodyweight",
    cue: "One foot at a time — full stretch at the bottom, pause at the top for balance.",
    primary: ["Gastrocnemius_Lateral_Medial", "Soleus"],
    secondary: [],
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    category: "Core",
    equipment: "Cable",
    cue: "Curl the spine, keep the hips stationary, squeeze hard.",
    primary: ["Rectus_Abdominis"],
    secondary: ["External_Oblique"],
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    category: "Core",
    equipment: "Bodyweight",
    cue: "Posterior pelvic tilt, control the swing, full range.",
    primary: ["Rectus_Abdominis", "Psoas_Major"],
    secondary: ["External_Oblique"],
  },
  {
    id: "plank",
    name: "Plank",
    category: "Core",
    equipment: "Bodyweight",
    cue: "Straight line head to heels, squeeze glutes, breathe.",
    primary: ["Rectus_Abdominis", "External_Oblique"],
    secondary: [],
  },
];

export const EXERCISE_CATEGORIES = ["Push", "Pull", "Legs", "Core"] as const;

export function getExercise(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}
