// Curated anatomical data for the major gym-relevant muscles.
// Keyed by the exact GLB node name. Muscles not in this map fall back to a formatted name.

export type MuscleInfo = {
  label: string;
  group: string; // gym group key (see groups.ts GYM_GROUPS)
  fn: string; // primary function
  origin: string;
  insertion: string;
  antagonist: string; // readable antagonist label
  exercises: string[]; // exercise ids (see exercises.ts)
};

export const MUSCLE_DATA: Record<string, MuscleInfo> = {
  Pectoralis_Major_Clavicular_Sternocostal_Abdominal: {
    label: "Pectoralis Major",
    group: "chest",
    fn: "Flexes, adducts and internally rotates the humerus — the main pressing muscle.",
    origin: "Clavicle, sternum, and cartilage of ribs 1–6.",
    insertion: "Lateral lip of the bicipital groove of the humerus.",
    antagonist: "Latissimus Dorsi / Trapezius",
    exercises: ["bench-press", "incline-db-press", "dips", "cable-fly", "push-up"],
  },
  Pectoralis_Minor: {
    label: "Pectoralis Minor",
    group: "chest",
    fn: "Stabilises the scapula by drawing it forward and downward.",
    origin: "Anterior surface of ribs 3–5.",
    insertion: "Coracoid process of the scapula.",
    antagonist: "Trapezius (lower fibres)",
    exercises: ["dips", "push-up"],
  },
  Latissimus_Dorsi: {
    label: "Latissimus Dorsi",
    group: "back",
    fn: "Extends, adducts and internally rotates the shoulder — drives all pulling.",
    origin: "Spinous processes T7–L5, thoracolumbar fascia, iliac crest.",
    insertion: "Floor of the intertubercular groove of the humerus.",
    antagonist: "Deltoid / Pectoralis Major",
    exercises: ["pull-up", "lat-pulldown", "barbell-row", "cable-row", "deadlift"],
  },
  Trapezius: {
    label: "Trapezius",
    group: "back",
    fn: "Elevates, retracts and rotates the scapula; supports the neck.",
    origin: "Occipital bone, nuchal ligament, spinous processes C7–T12.",
    insertion: "Clavicle, acromion, and spine of the scapula.",
    antagonist: "Serratus Anterior (lower fibres)",
    exercises: ["barbell-row", "face-pull", "deadlift", "shrug"],
  },
  Rhomboideus_Major: {
    label: "Rhomboid Major",
    group: "back",
    fn: "Retracts and rotates the scapula toward the spine.",
    origin: "Spinous processes T2–T5.",
    insertion: "Medial border of the scapula.",
    antagonist: "Serratus Anterior",
    exercises: ["barbell-row", "cable-row", "face-pull"],
  },
  Teres_Major: {
    label: "Teres Major",
    group: "back",
    fn: "Adducts and internally rotates the humerus; assists the lats.",
    origin: "Inferior angle of the scapula.",
    insertion: "Medial lip of the intertubercular groove of the humerus.",
    antagonist: "Deltoid",
    exercises: ["pull-up", "lat-pulldown", "barbell-row"],
  },
  Deltoid_Anterior_Middle_Posterior: {
    label: "Deltoid",
    group: "shoulders",
    fn: "Abducts, flexes and extends the shoulder across three heads.",
    origin: "Clavicle, acromion, and spine of the scapula.",
    insertion: "Deltoid tuberosity of the humerus.",
    antagonist: "Latissimus Dorsi",
    exercises: ["overhead-press", "lateral-raise", "face-pull", "incline-db-press"],
  },
  Infraspinatus: {
    label: "Infraspinatus",
    group: "shoulders",
    fn: "Externally rotates and stabilises the shoulder (rotator cuff).",
    origin: "Infraspinous fossa of the scapula.",
    insertion: "Greater tubercle of the humerus.",
    antagonist: "Subscapularis",
    exercises: ["face-pull", "cuban-rotation"],
  },
  Supraspinatus: {
    label: "Supraspinatus",
    group: "shoulders",
    fn: "Initiates abduction of the arm; stabilises the humeral head.",
    origin: "Supraspinous fossa of the scapula.",
    insertion: "Greater tubercle of the humerus.",
    antagonist: "Latissimus Dorsi",
    exercises: ["lateral-raise", "cuban-rotation"],
  },
  Subscapularis: {
    label: "Subscapularis",
    group: "shoulders",
    fn: "Internally rotates the shoulder (rotator cuff stabiliser).",
    origin: "Subscapular fossa of the scapula.",
    insertion: "Lesser tubercle of the humerus.",
    antagonist: "Infraspinatus / Teres Minor",
    exercises: ["cuban-rotation"],
  },
  Serratus_Anterior: {
    label: "Serratus Anterior",
    group: "chest",
    fn: "Protracts and upwardly rotates the scapula ('boxer's muscle').",
    origin: "Outer surfaces of ribs 1–8.",
    insertion: "Medial border of the scapula (anterior).",
    antagonist: "Rhomboids",
    exercises: ["push-up", "overhead-press"],
  },
  Biceps_Brachii: {
    label: "Biceps Brachii",
    group: "arms",
    fn: "Flexes the elbow and supinates the forearm.",
    origin: "Supraglenoid tubercle (long head) & coracoid process (short head).",
    insertion: "Radial tuberosity and bicipital aponeurosis.",
    antagonist: "Triceps Brachii",
    exercises: ["db-curl", "barbell-curl", "pull-up", "lat-pulldown"],
  },
  Brachialis: {
    label: "Brachialis",
    group: "arms",
    fn: "Pure elbow flexor — the workhorse beneath the biceps.",
    origin: "Distal anterior humerus.",
    insertion: "Coronoid process and tuberosity of the ulna.",
    antagonist: "Triceps Brachii",
    exercises: ["db-curl", "barbell-curl"],
  },
  Triceps_Lateral_Long_Heads: {
    label: "Triceps Brachii (Lateral & Long Head)",
    group: "arms",
    fn: "Extends the elbow; the long head also extends the shoulder.",
    origin: "Infraglenoid tubercle (long) & posterior humerus (lateral).",
    insertion: "Olecranon process of the ulna.",
    antagonist: "Biceps Brachii",
    exercises: ["tricep-pushdown", "dips", "bench-press", "overhead-press"],
  },
  Triceps_Medial_Head: {
    label: "Triceps Brachii (Medial Head)",
    group: "arms",
    fn: "Extends the elbow through the full range of motion.",
    origin: "Posterior surface of the distal humerus.",
    insertion: "Olecranon process of the ulna.",
    antagonist: "Biceps Brachii",
    exercises: ["tricep-pushdown", "dips"],
  },
  Brachioradialis: {
    label: "Brachioradialis",
    group: "forearms",
    fn: "Flexes the elbow, strongest in the neutral grip.",
    origin: "Lateral supracondylar ridge of the humerus.",
    insertion: "Styloid process of the radius.",
    antagonist: "Triceps Brachii",
    exercises: ["db-curl", "barbell-curl"],
  },
  Rectus_Abdominis: {
    label: "Rectus Abdominis",
    group: "core",
    fn: "Flexes the trunk and resists extension — the 'six-pack'.",
    origin: "Pubic crest and pubic symphysis.",
    insertion: "Xiphoid process and costal cartilages of ribs 5–7.",
    antagonist: "Erector Spinae",
    exercises: ["cable-crunch", "hanging-leg-raise", "plank"],
  },
  External_Oblique: {
    label: "External Oblique",
    group: "core",
    fn: "Rotates and laterally flexes the trunk; compresses the abdomen.",
    origin: "External surfaces of ribs 5–12.",
    insertion: "Iliac crest and linea alba.",
    antagonist: "Opposite-side oblique",
    exercises: ["cable-crunch", "plank", "hanging-leg-raise"],
  },
  Psoas_Major: {
    label: "Psoas Major",
    group: "core",
    fn: "Primary hip flexor; stabilises the lumbar spine.",
    origin: "Bodies & transverse processes of T12–L5.",
    insertion: "Lesser trochanter of the femur.",
    antagonist: "Gluteus Maximus",
    exercises: ["hanging-leg-raise"],
  },
  Gluteus_Maximus: {
    label: "Gluteus Maximus",
    group: "glutes",
    fn: "Extends and externally rotates the hip — the body's strongest muscle.",
    origin: "Posterior ilium, sacrum and coccyx.",
    insertion: "Iliotibial tract and gluteal tuberosity of the femur.",
    antagonist: "Iliopsoas (hip flexors)",
    exercises: ["squat", "hip-thrust", "deadlift", "lunge", "rdl"],
  },
  Gluteus_Medius: {
    label: "Gluteus Medius",
    group: "glutes",
    fn: "Abducts the hip and stabilises the pelvis when walking.",
    origin: "Outer surface of the ilium.",
    insertion: "Greater trochanter of the femur.",
    antagonist: "Adductors",
    exercises: ["hip-thrust", "lunge", "squat"],
  },
  Gluteus_Minimus: {
    label: "Gluteus Minimus",
    group: "glutes",
    fn: "Abducts and internally rotates the hip; pelvic stabiliser.",
    origin: "Outer surface of the ilium (below medius).",
    insertion: "Greater trochanter of the femur.",
    antagonist: "Adductors",
    exercises: ["hip-thrust", "lunge"],
  },
  Rectus_Femoris: {
    label: "Rectus Femoris",
    group: "quads",
    fn: "Extends the knee and flexes the hip (only quad crossing both).",
    origin: "Anterior inferior iliac spine.",
    insertion: "Patella, then tibial tuberosity via patellar ligament.",
    antagonist: "Hamstrings",
    exercises: ["squat", "leg-press", "leg-extension", "lunge"],
  },
  Vastus_Lateralis: {
    label: "Vastus Lateralis",
    group: "quads",
    fn: "Extends the knee — the largest of the quadriceps.",
    origin: "Greater trochanter and lateral linea aspera of the femur.",
    insertion: "Patella via the quadriceps tendon.",
    antagonist: "Hamstrings",
    exercises: ["squat", "leg-press", "leg-extension"],
  },
  Vastus_Medialis: {
    label: "Vastus Medialis",
    group: "quads",
    fn: "Extends the knee; the teardrop that stabilises the kneecap.",
    origin: "Medial linea aspera of the femur.",
    insertion: "Patella via the quadriceps tendon.",
    antagonist: "Hamstrings",
    exercises: ["squat", "leg-press", "leg-extension"],
  },
  Vastus_Intermedius: {
    label: "Vastus Intermedius",
    group: "quads",
    fn: "Extends the knee; sits deep between the other vasti.",
    origin: "Anterior and lateral femoral shaft.",
    insertion: "Patella via the quadriceps tendon.",
    antagonist: "Hamstrings",
    exercises: ["squat", "leg-press", "leg-extension"],
  },
  Biceps_Femoris_Long_Head: {
    label: "Biceps Femoris (Long Head)",
    group: "hamstrings",
    fn: "Flexes the knee and extends the hip.",
    origin: "Ischial tuberosity.",
    insertion: "Head of the fibula.",
    antagonist: "Quadriceps",
    exercises: ["rdl", "leg-curl", "deadlift", "hip-thrust"],
  },
  Biceps_Femoris_Short_Head: {
    label: "Biceps Femoris (Short Head)",
    group: "hamstrings",
    fn: "Flexes the knee.",
    origin: "Lateral linea aspera of the femur.",
    insertion: "Head of the fibula.",
    antagonist: "Quadriceps",
    exercises: ["leg-curl", "rdl"],
  },
  Semitendinosus: {
    label: "Semitendinosus",
    group: "hamstrings",
    fn: "Flexes the knee and extends the hip.",
    origin: "Ischial tuberosity.",
    insertion: "Medial surface of the tibia (pes anserinus).",
    antagonist: "Quadriceps",
    exercises: ["rdl", "leg-curl", "deadlift"],
  },
  Semimembranosus: {
    label: "Semimembranosus",
    group: "hamstrings",
    fn: "Flexes the knee and extends the hip.",
    origin: "Ischial tuberosity.",
    insertion: "Medial condyle of the tibia.",
    antagonist: "Quadriceps",
    exercises: ["rdl", "leg-curl"],
  },
  Adductor_Magnus: {
    label: "Adductor Magnus",
    group: "adductors",
    fn: "Adducts and extends the hip — large inner-thigh muscle.",
    origin: "Ischiopubic ramus and ischial tuberosity.",
    insertion: "Linea aspera and adductor tubercle of the femur.",
    antagonist: "Gluteus Medius",
    exercises: ["squat", "lunge", "hip-thrust"],
  },
  Adductor_Longus: {
    label: "Adductor Longus",
    group: "adductors",
    fn: "Adducts and flexes the hip.",
    origin: "Body of the pubis.",
    insertion: "Middle third of the linea aspera.",
    antagonist: "Gluteus Medius",
    exercises: ["squat", "lunge"],
  },
  Gracilis: {
    label: "Gracilis",
    group: "adductors",
    fn: "Adducts the hip and flexes the knee.",
    origin: "Body and inferior ramus of the pubis.",
    insertion: "Medial tibia (pes anserinus).",
    antagonist: "Gluteus Medius",
    exercises: ["squat", "lunge"],
  },
  Gastrocnemius_Lateral_Medial: {
    label: "Gastrocnemius",
    group: "calves",
    fn: "Plantarflexes the ankle and flexes the knee — the diamond calf.",
    origin: "Medial and lateral condyles of the femur.",
    insertion: "Calcaneus via the Achilles tendon.",
    antagonist: "Tibialis Anterior",
    exercises: ["standing-calf-raise", "calf-raise"],
  },
  Soleus: {
    label: "Soleus",
    group: "calves",
    fn: "Plantarflexes the ankle; key for standing endurance.",
    origin: "Posterior tibia and fibula.",
    insertion: "Calcaneus via the Achilles tendon.",
    antagonist: "Tibialis Anterior",
    exercises: ["seated-calf-raise", "calf-raise"],
  },
  Tibialis_Anterior: {
    label: "Tibialis Anterior",
    group: "calves",
    fn: "Dorsiflexes and inverts the foot.",
    origin: "Lateral condyle and upper tibia.",
    insertion: "Medial cuneiform and first metatarsal.",
    antagonist: "Gastrocnemius / Soleus",
    exercises: ["tibialis-raise"],
  },
  Sternocleidomastoid: {
    label: "Sternocleidomastoid",
    group: "back",
    fn: "Flexes and rotates the neck.",
    origin: "Sternum and clavicle.",
    insertion: "Mastoid process of the temporal bone.",
    antagonist: "Splenius Capitis",
    exercises: [],
  },
};

export function getMuscleInfo(nodeName: string): MuscleInfo | null {
  return MUSCLE_DATA[nodeName] || null;
}
